### ISSUE TITLE
Can't remove dead apps from GUI list

### ISSUE THREAD

**Issue by orrinwitt** [truenas/apps#1131]
/I have been struggling to get a custom app to install and work correctly, which has required me to delete it and start over several times. A couple of those times, the app remains in the apps list, even though all the containers, volumes, and networks associated with them are gone (confirmed via cli). 

The specific error is: `[EFAULT] Failed 'down' action` whenever I attempt to delete the listing from the GUI.

This is really annoying, expecially as it prevents me from re-using the name of the application if it matches the dead/orphaned listing.
![Screenshot 2024-12-05 140106](https://github.com/user-attachments/assets/e004fe51-2e44-400e-95c6-7fb696b98ac5)
![Screenshot 2024-12-05 140146](https://github.com/user-attachments/assets/667fdc5f-0531-4544-9693-8c338effebf9)

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 344, in do_delete
    return self.delete_internal(job, app_name, app_config, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 349, in delete_internal
    compose_action(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 57, in compose_action
    raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed 'down' action for 'nextcloud' app, please check /var/log/app_lifecycle.log for more details
```

**Comment by stavros-k** [comment]
Have you tried looking into `/var/log/app_lifecycle.log` as the error suggests?
What is the contents of this file?

**Comment by stavros-k** [comment]
Edit the yaml file and remove the networks and environment section.
Docker won't delete something if its compose file is invalid.
