### ISSUE TITLE
Vaultwarden k8s to docker migration fails

### ISSUE THREAD

**Issue by hardysim** [truenas/apps#1147]
I've updated TrueNAS from 24.04 to 24.10 and my vaultwarden app did not migrate.

I get a notification in TrueNAS:

```
Error
App(s) failed to migrate, please check /var/log/app_migrations.log for more details.
2024-12-08 13:45:57 (Europe/Berlin)
```

The corresponding error in there is:

```
[2024/12/08 13:45:57] (DEBUG) app_migrations.migrate():241 - 'vaultwarden' app failed to migrate successfully: 'Failed to create app: [EFAULT] Failed to render compose templates: Traceback (most recent call last):\n  File "/usr/bin/apps_render_app", line 33, in <module>\n    sys.exit(load_entry_point(\'apps-validation==0.1\', \'console_scripts\', \'apps_render_app\')())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main\n    render_templates_from_path(args.path, args.values)\n  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path\n    rendered_data = render_templates(\n                    ^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates\n    ).render({\'ix_lib\': template_libs, \'values\': test_values})\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render\n    self.environment.handle_exception()\n  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File "/mnt/.ix-apps/app_configs/vaultwarden/versions/1.1.11/templates/docker-compose.yaml", line 59, in top-level template code\n    {{ tpl.render() | tojson }}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/app_configs/vaultwarden/versions/1.1.11/templates/library/base_v2_0_21/render.py", line 69, in render\n    "services": {c._name: c.render() for c in self._containers.values()},\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/app_configs/vaultwarden/versions/1.1.11/templates/library/base_v2_0_21/render.py", line 69, in <dictcomp>\n    "services": {c._name: c.render() for c in self._containers.values()},\n                          ^^^^^^^^^^\n  File "/mnt/.ix-apps/app_configs/vaultwarden/versions/1.1.11/templates/library/base_v2_0_21/container.py", line 280, in render\n    result["environment"] = self.environment.render()\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/app_configs/vaultwarden/versions/1.1.11/templates/library/base_v2_0_21/environment.py", line 106, in render\n    raise RenderError(f"Environment variable [{k}] is already defined from the application developer.")\nbase_v2_0_21.error.RenderError: Environment variable [ADMIN_TOKEN] is already defined from the application developer.\n'
```

This seems "correct" since I had some environment variables set in the old k8s app config and one of them was `ADMIN_TOKEN`. In the new docker app config this is a dedicated setting besides the environment variables. But there's no hint for this in the [release notes](https://www.truenas.com/docs/scale/24.10/gettingstarted/scalereleasenotes/#preparing-for-app-migration:~:text=Automatic%20app%20migration%20on%20upgrade%20from%2024.04%20is%20at%20parity%20for%20all%20official%20catalog%20applications.%20A%20few%20applications%20might%20require%20manual%20migration%20steps%2C%20depending%20on%20the%20options%20enabled%20in%2024.04.).

---

Next, I tried to just create a new app from scratch and attach my old host path storage to it but it now **requires** a `Database Password` which I did not specify in the old k8s app config. Using a random, new password does not work and I get endless error messages like this one when checking the `vaultwarden` container log (the `postgres` container is `Running`):

```
2024-12-08 13:10:32.440375+00:00[2024-12-08 14:10:32.440][vaultwarden][ERROR] Error creating database pool: DieselCon.
2024-12-08 13:10:32.440410+00:00[CAUSE] BadConnection(
2024-12-08 13:10:32.440444+00:00"connection to server at \"postgres\" (172.16.3.2), port 5432 failed: FATAL:  password authentication failed for user \"vaultwarden\"\n",
```

Which seems "correct" as well since my old database didn't had a password set (or I don't know the default password from the old k8s installation).

---

- What's the (default?) database password from the old k8s app installation?
- Should one attach a hint for these problems to the [upgrade notes](https://www.truenas.com/docs/scale/24.10/gettingstarted/scalereleasenotes/#upgrade-notes)?

**Comment by hardysim** [comment]
I've found some kind of credentials in `/mnt/pool/ix-applications/backups/system-update--2024-12-08_12:37:12/vaultwarden/secrets/vaultwarden-postgres-creds`
but it seems that the password mentioned there is hashed and using it untouched in the new docker app config does not work and results in the same `password authentication failed` error .

**Comment by hardysim** [comment]
Uhh, it's just Base64 encoded. Decoding the password from this file and using it in the docker app config is working. The app is now starting just fine and my vault is accessible.

**Comment by hardysim** [comment]
I'm leaving this issue open so someone from the TrueNAS team sees it and maybe adds a hint to the upgrade notes about this issue.

**Comment by stavros-k** [comment]
Hello, there was a field in the k8s version for admin token as well.
The difference was that on k8s version we were only setting the `ADMIN_TOKEN` when user provided value, but not we do it all the time.

I think it was because VW use it as a tri-state option.
set and "" == no admin panel
unset == use the config.json thing
set and non "" == admin panel

You would have the same error in k8s version if you had both admin token field set and the env variable

As for getting things off the k8s secret values, you can see an one liner here
https://github.com/truenas/apps/issues/712#issuecomment-2444060042
