### ISSUE TITLE
plex-auto-languages stuck in deploying

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#309]
Hi!

The app plex-auto-languages is not working yet. 

The container `permission` returns this info log:
```2024-08-29 21:29:00.863189+00:00Path [/mnt/plex-auto-] does is not a directory, skipping...```

The container `plex-auto-languages` returns this error log:
```
2024-08-29 21:29:02.825997+00:00[38;5;39m2024-08-29 23:29:02,825 [INFO] Setting value of parameter PLEX_URL from environment variable[0m
2024-08-29 21:29:02.826110+00:00[38;5;39m2024-08-29 23:29:02,825 [INFO] Setting value of parameter PLEX_TOKEN from environment variable[0m
2024-08-29 21:29:02.826422+00:00[38;5;39m2024-08-29 23:29:02,826 [INFO] The provided configuration has been successfully validated[0m
2024-08-29 21:29:02.827142+00:00[38;5;39m2024-08-29 23:29:02,826 [INFO] Starting scheduler[0m
2024-08-29 21:29:03.150052+00:00[38;5;39m2024-08-29 23:29:03,149 [INFO] Successfully connected as user '-Simo01' (id: 1)[0m
2024-08-29 21:29:03.151269+00:00Traceback (most recent call last):
2024-08-29 21:29:03.151318+00:00File "main.py", line 118, in <module>
2024-08-29 21:29:03.151354+00:00plex_auto_languages.start()
2024-08-29 21:29:03.151369+00:00File "main.py", line 68, in start
2024-08-29 21:29:03.151384+00:00self.init()
2024-08-29 21:29:03.151398+00:00File "main.py", line 45, in init
2024-08-29 21:29:03.151412+00:00self.plex = PlexServer(self.config.get("plex.url"), self.config.get("plex.token"), self.notifier, self.config)
2024-08-29 21:29:03.151436+00:00File "/app/plex_auto_languages/plex_server.py", line 110, in __init__
2024-08-29 21:29:03.151451+00:00self.cache = PlexServerCache(self)
2024-08-29 21:29:03.151465+00:00File "/app/plex_auto_languages/plex_server_cache.py", line 25, in __init__
2024-08-29 21:29:03.151487+00:00self._cache_file_path = self._get_cache_file_path()
2024-08-29 21:29:03.151501+00:00File "/app/plex_auto_languages/plex_server_cache.py", line 106, in _get_cache_file_path
2024-08-29 21:29:03.151515+00:00os.makedirs(cache_dir)
2024-08-29 21:29:03.151529+00:00File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
2024-08-29 21:29:03.151549+00:00mkdir(name, mode)
2024-08-29 21:29:03.151563+00:00PermissionError: [Errno 13] Permission denied: '/config/cache'
```

I've tried to look at the code but it is still not super clear how it works for me, but my guess is that it might be this space in this line:
`/mnt/plex-auto-  languages/config`
https://github.com/truenas/apps/blob/27cef5c90a0fb70b206275f8ca3f411c9fbb31ae/ix-dev/community/plex-auto-languages/templates/docker-compose.yaml#L13

Thanks!

**Comment by stavros-k** [comment]
Thanks!
