### ISSUE TITLE
Can't install any app from GHCR.IO

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#314]
Hi!

I'm trying to install the *arr stack but I got this error:
**SONARR**
```[EFAULT] Failed 'up' action for 'sonarr' app: sonarr Pulling sonarr Error Head "https://ghcr.io/v2/onedr0p/sonarr/manifests/4.0.9.2244": denied: denied Error response from daemon: Head "https://ghcr.io/v2/onedr0p/sonarr/manifests/4.0.9.2244": denied: denied```
**RADARR**
```[EFAULT] Failed 'up' action for 'radarr' app: radarr Pulling radarr Error Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied Error response from daemon: Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied```
**BAZARR**
```[EFAULT] Failed 'up' action for 'bazarr' app: bazarr Pulling bazarr Error Head "https://ghcr.io/v2/onedr0p/bazarr/manifests/1.4.3": denied: denied Error response from daemon: Head "https://ghcr.io/v2/onedr0p/bazarr/manifests/1.4.3": denied: denied```

Full log:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'bazarr' app:  bazarr Pulling 
 bazarr Error Head "https://ghcr.io/v2/onedr0p/bazarr/manifests/1.4.3": denied: denied
Error response from daemon: Head "https://ghcr.io/v2/onedr0p/bazarr/manifests/1.4.3": denied: denied


```

### UPDATE:
I got the same issue with `audiobookshelf`, so it could be some issue with the host `https://ghcr.io`

`
[EFAULT] Failed 'up' action for 'audiobookshelf' app: audiobookshelf Pulling audiobookshelf Error Head "https://ghcr.io/v2/advplyr/audiobookshelf/manifests/2.12.3": denied: denied Error response from daemon: Head "https://ghcr.io/v2/advplyr/audiobookshelf/manifests/2.12.3": denied: denied
`

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'audiobookshelf' app:  audiobookshelf Pulling 
 audiobookshelf Error Head "https://ghcr.io/v2/advplyr/audiobookshelf/manifests/2.12.3": denied: denied
Error response from daemon: Head "https://ghcr.io/v2/advplyr/audiobookshelf/manifests/2.12.3": denied: denied


```

**Comment by Simoneu01** [comment]
Update, I've tried to use the manual pull and I got the same issue:

![image](https://github.com/user-attachments/assets/5d89f3e5-e80b-4a2c-a58f-c0f59e9ce8ed)

`[EFAULT] Failed to pull 'ghcr.io/onedr0p/sonarr:latest' image: 500 Server Error for http+docker://localhost/v1.46/images/create?tag=latest&fromImage=ghcr.io%2Fonedr0p%2Fsonarr: Internal Server Error ("Head "https://ghcr.io/v2/onedr0p/sonarr/manifests/latest": denied: denied")`


```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.46/images/create?tag=latest&fromImage=ghcr.io%2Fonedr0p%2Fsonarr

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/docker/images.py", line 36, in pull_image
    response = client.api.pull(image_tag, auth_config=auth_config, stream=True, decode=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.46/images/create?tag=latest&fromImage=ghcr.io%2Fonedr0p%2Fsonarr: Internal Server Error ("Head "https://ghcr.io/v2/onedr0p/sonarr/manifests/latest": denied: denied")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps_images/images.py", line 115, in pull
    pull_image(image_tag, callback, auth_config.get('username'), auth_config.get('password'))
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/docker/images.py", line 41, in pull_image
    raise CallError(f'Failed to pull {image_tag!r} image: {e!s}')
middlewared.service_exception.CallError: [EFAULT] Failed to pull 'ghcr.io/onedr0p/sonarr:latest' image: 500 Server Error for http+docker://localhost/v1.46/images/create?tag=latest&fromImage=ghcr.io%2Fonedr0p%2Fsonarr: Internal Server Error ("Head "https://ghcr.io/v2/onedr0p/sonarr/manifests/latest": denied: denied")

```

**Comment by stavros-k** [comment]
Can you check again now? It was probably this:
https://www.githubstatus.com/incidents/345t4sjty6q3

**Comment by Simoneu01** [comment]
> Can you check again now? It was probably this: https://www.githubstatus.com/incidents/345t4sjty6q3

![image](https://github.com/user-attachments/assets/0c21aa4a-b6ee-45af-b1e1-62d3ff0dd9c3)
Still not working


```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'radarr' app:  radarr Pulling 
 radarr Error Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied
Error response from daemon: Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied

```

**Comment by Simoneu01** [comment]
@stavros-k Do you also have the same issue? Or is it something that affects only me?

**Comment by stavros-k** [comment]
I dont have that, no.
But note that I'm running nightlies. `ElectricEel-24.10.0-MASTER-20240829-030407`

**Comment by Simoneu01** [comment]
I guess I'll have to switch to the nightly because without ghcr.io I can't do anything 😅

**Comment by Simoneu01** [comment]
@stavros-k I got the same error even with your same nightlies

result of the manifest `https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070`
```
{
    "errors": [
        {
            "code": "UNAUTHORIZED",
            "message": "authentication required"
        }
    ]
}
```

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 480, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 524, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1363, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1360, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'radarr' app:  radarr Pulling 
 radarr Error Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied
Error response from daemon: Head "https://ghcr.io/v2/onedr0p/radarr/manifests/5.9.1.9070": denied: denied

```

**Comment by Simoneu01** [comment]
I've found the solution, I was logged in with my credentials to ghcr.io (used to run a private custom app with K3s in Truenas Scale Cobia.

For other user references, I've fixed the error manually by removing this file `~/.docker/config.json` that had a previous (now expired) token

Thank you @stavros-k and sorry for bothering you

**Comment by stavros-k** [comment]
Ah, thanks for sharing that! 
No worries!
