### ISSUE TITLE
Can't install immich app

### ISSUE THREAD

**Issue by Simoneu01** [truenas/apps#366]
Hi!

I'm trying to install Immich and I'm getting this error:
```
[EFAULT] Failed 'up' action for 'immich' app: Network ix-immich_default 
Creating Network ix-immich_default 
Created Container ix-immich-permissions-1 
Creating Container ix-immich-permissions-1 
Created Container ix-immich-pgvecto-1 
Creating Container ix-immich-redis-1 
Creating Container ix-immich-redis-1 
Created Container ix-immich-pgvecto-1 
Created Container ix-immich-server-1 
Creating Container ix-immich-server-1 
Created Container ix-immich-permissions-1 
Starting Container ix-immich-permissions-1 
Started Container ix-immich-permissions-1 
Waiting Container ix-immich-permissions-1 
Waiting Container ix-immich-permissions-1 
Exited Container ix-immich-redis-1 
Starting Container ix-immich-permissions-1 
Exited Container ix-immich-pgvecto-1 
Starting Container ix-immich-pgvecto-1 
Started Container ix-immich-redis-1 
Started Container ix-immich-pgvecto-1 
Waiting Container ix-immich-redis-1 
Waiting Container ix-immich-permissions-1 
Waiting Container ix-immich-permissions-1 
Exited Container ix-immich-pgvecto-1 
Error Container ix-immich-redis-1 
Healthy dependency failed to start: container ix-immich-pgvecto-1 is unhealthy
```

Traceback:
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'immich' app:  Network ix-immich_default  Creating
 Network ix-immich_default  Created
 Container ix-immich-permissions-1  Creating
 Container ix-immich-permissions-1  Created
 Container ix-immich-pgvecto-1  Creating
 Container ix-immich-redis-1  Creating
 Container ix-immich-redis-1  Created
 Container ix-immich-pgvecto-1  Created
 Container ix-immich-server-1  Creating
 Container ix-immich-server-1  Created
 Container ix-immich-permissions-1  Starting
 Container ix-immich-permissions-1  Started
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-redis-1  Starting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-pgvecto-1  Starting
 Container ix-immich-pgvecto-1  Started
 Container ix-immich-redis-1  Started
 Container ix-immich-pgvecto-1  Waiting
 Container ix-immich-redis-1  Waiting
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-pgvecto-1  Error
 Container ix-immich-redis-1  Healthy
dependency failed to start: container ix-immich-pgvecto-1 is unhealthy
```

Storage Configuration:
I'm using the host path for all the paths, these are the perms on the datasets:
![image](https://github.com/user-attachments/assets/4d7f1ffe-65f9-4792-b5ee-18a902b6d5e1)

**Comment by stavros-k** [comment]
Database directory needs `999:999`
You will soon be able to see those details before installing the app 
(See https://ixsystems.atlassian.net/browse/NAS-130884)

**Comment by gr3k** [comment]
@stavros-k I have similar issue. with Nextcloud postresql directory too:
I set permission to db directory, but it doesn't help.
Could you advice how to set proper permission to own (Host Path) path ? 

  │  /mnt/NVMe/APPS/Immich  ls -lah                                                             ✔ │ root@truenas │ 10:37:32  
total 116K
drwxrwx--- 8 root    root   8 Sep  6 10:29 .
drwxrwx--- 9 apps    apps   9 Sep  6 10:25 ..
drwxrwx--- 2 root    root   2 Sep  6 10:25 Immich-library
drwxrwx--- 2 netdata docker 2 Sep  6 10:37 Immich-postgres-db
drwxrwx--- 2 root    root   2 Sep  6 10:27 Immich-profile
drwxrwx--- 2 root    root   2 Sep  6 10:27 Immich-thumbs
drwxrwx--- 2 root    root   2 Sep  6 10:26 Immich-uploads
drwxrwx--- 2 root    root   2 Sep  6 10:28 Immich-video
  │  /mnt/NVMe/APPS/Immich  ls -n                                                               ✔ │ root@truenas │ 10:37:34  
total 99
drwxrwx--- 2   0   0 2 Sep  6 10:25 Immich-library
drwxrwx--- 2 999 999 2 Sep  6 10:37 Immich-postgres-db
drwxrwx--- 2   0   0 2 Sep  6 10:27 Immich-profile
drwxrwx--- 2   0   0 2 Sep  6 10:27 Immich-thumbs
drwxrwx--- 2   0   0 2 Sep  6 10:26 Immich-uploads
drwxrwx--- 2   0   0 2 Sep  6 10:28 Immich-video


<img width="1169" alt="image" src="https://github.com/user-attachments/assets/bdc95d6a-62b3-4d5e-8e78-e21933266a7e">

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 513, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1356, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 195, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 244, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 232, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 52, in compose_action
    raise CallError(f'Failed {action!r} action for {app_name!r} app: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'immich' app:  Network ix-immich_default  Creating
 Network ix-immich_default  Created
 Container ix-immich-permissions-1  Creating
 Container ix-immich-permissions-1  Created
 Container ix-immich-redis-1  Creating
 Container ix-immich-machine-learning-1  Creating
 Container ix-immich-pgvecto-1  Creating
 Container ix-immich-pgvecto-1  Created
 Container ix-immich-redis-1  Created
 Container ix-immich-machine-learning-1  Created
 Container ix-immich-server-1  Creating
 Container ix-immich-server-1  Created
 Container ix-immich-permissions-1  Starting
 Container ix-immich-permissions-1  Started
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-redis-1  Starting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-pgvecto-1  Starting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-machine-learning-1  Starting
 Container ix-immich-redis-1  Started
 Container ix-immich-pgvecto-1  Started
 Container ix-immich-machine-learning-1  Started
 Container ix-immich-pgvecto-1  Waiting
 Container ix-immich-redis-1  Waiting
 Container ix-immich-permissions-1  Waiting
 Container ix-immich-permissions-1  Exited
 Container ix-immich-pgvecto-1  Error
 Container ix-immich-redis-1  Healthy
dependency failed to start: container ix-immich-pgvecto-1 is unhealthy

**Comment by stavros-k** [comment]
@gr3k Permissions looks good to me.
While installing, can you have an additional shell window with `docker logs ix-immich-pgvecto-1 -f` running?
So we can see some info as to why it is failing to start?

Thanks

**Comment by gr3k** [comment]
@stavros-k thanks for the tip. 
My issue was 'to open' permissions. I reduce it and now deploy finish without errors.
Maybe it would be good to mention about it in the application description or something ? 

Before:
` docker logs ix-immich-pgvecto-1 -f                                                                 ✔ │ root@truenas │ 12:23:10  
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2024-09-11 10:23:11.671 UTC [69] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2024-09-11 10:23:11.671 UTC [69] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
2024-09-11 10:23:16.960 UTC [69] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2024-09-11 10:23:16.960 UTC [69] DETAIL:  **Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).**
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... #      `

**After permission change:**

<img width="509" alt="image" src="https://github.com/user-attachments/assets/313ef6c4-d8cd-43b4-ba0d-a605a558854f">

<img width="612" alt="image" src="https://github.com/user-attachments/assets/ee141193-0cbf-4dba-a190-b0760fe0bc2b">

`docker logs ix-immich-pgvecto-1 -f                                             ✔ │ root@truenas │ 12:28:53  
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:
initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-09-11 10:28:55.214 UTC [34] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-09-11 10:28:55.215 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-11 10:28:55.218 UTC [37] LOG:  database system was shut down at 2024-09-11 10:28:55 UTC
2024-09-11 10:28:55.221 UTC [34] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2024-09-11 10:28:55.400 UTC [34] LOG:  received fast shutdown request
waiting for server to shut down....2024-09-11 10:28:55.401 UTC [34] LOG:  aborting any active transactions
2024-09-11 10:28:55.402 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
2024-09-11 10:28:55.402 UTC [35] LOG:  shutting down
2024-09-11 10:28:55.402 UTC [35] LOG:  checkpoint starting: shutdown immediate
2024-09-11 10:28:55.517 UTC [35] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.108 s, total=0.115 s; sync files=301, longest=0.002 s, average=0.001 s; distance=4223 kB, estimate=4223 kB
2024-09-11 10:28:55.521 UTC [34] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2024-09-11 10:28:55.619 UTC [1] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-09-11 10:28:55.620 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-09-11 10:28:55.620 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-09-11 10:28:55.621 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-11 10:28:55.624 UTC [53] LOG:  database system was shut down at 2024-09-11 10:28:55 UTC
2024-09-11 10:28:55.627 UTC [1] LOG:  database system is ready to accept connections
2024-09-11 10:29:20.879 UTC [51] LOG:  checkpoints are occurring too frequently (25 seconds apart)
2024-09-11 10:29:20.879 UTC [51] HINT:  Consider increasing the configuration parameter "max_wal_size".
2024-09-11 10:29:20.879 UTC [51] LOG:  checkpoint starting: wal`

**Comment by stavros-k** [comment]
Soon will be a card showing some basic info about "run as" context, (ticket shared above).
But I agree this won't convey all the information needed always.

I do have in my todo's to find a way to provide more info about that later on.
That would be more clear as to what is needed!

I'll close this one now, as the main issue is solved

Thanks for letting me know!
