### ISSUE TITLE
Zerotier fails to migrate to 24.10-RC1

### ISSUE THREAD

**Issue by yichi-yang** [truenas/apps#587]
Found this line in `/var/log/app_migrations.log`:
```
[2024/10/02 10:16:41] (DEBUG) app_migrations.migrate():231 - 'zerotier' app failed to migrate successfully: 'Failed to migrate config: Failed to migrate config: Traceback (most recent call last):\n  File "/mnt/.ix-apps/truenas_catalog/trains/community/zerotier/1.0.15/migrations/migrate_from_kubernetes", line 45, in <module>\n    print(yaml.dump(migrate(yaml.safe_load(f.read()))))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/truenas_catalog/trains/community/zerotier/1.0.15/migrations/migrate_from_kubernetes", line 30, in migrate\n    for item in config["zerotierStorage"]["additionalStorages"]\n                ~~~~~~^^^^^^^^^^^^^^^^^^^\nKeyError: \'zerotierStorage\'\n'
```
Formatted traceback:
```
Failed to migrate config: Failed to migrate config: Traceback (most recent call last):
  File "/mnt/.ix-apps/truenas_catalog/trains/community/zerotier/1.0.15/migrations/migrate_from_kubernetes", line 45, in <module>
    print(yaml.dump(migrate(yaml.safe_load(f.read()))))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/truenas_catalog/trains/community/zerotier/1.0.15/migrations/migrate_from_kubernetes", line 30, in migrate
    for item in config["zerotierStorage"]["additionalStorages"]
                ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'zerotierStorage'
```

**Comment by stavros-k** [comment]
Hello,
Did you updated your apps to the latest version before upgrading TrueNAS?

**Comment by yichi-yang** [comment]
Ah good point... I'm fairly sure I didn't. Is there are way to recover from that (or I guess I'll just install a new instance)?

**Comment by stavros-k** [comment]
In this case the fix can be easily handled.
once the linked PR above is merged you can refresh the catalog and re-run the migration
