### ISSUE TITLE
Electric Eel Migration Error: config["storjConfig"] is undefined

### ISSUE THREAD

**Issue by nickles-lee** [truenas/apps#621]
The migration for one of my two Storj apps failed when migrating to Electric Eel RC2. 
```
[2024/10/06 13:44:07] (DEBUG) app_migrations.migrate():231 - 'storj' app failed to migrate successfully: 'Failed to migrate config: Failed to migrate config: Traceback (most recent call last):\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/storj/1.1.8/migrations/migrate_from_kubernetes", line 65, in <module>\n    print(yaml.dump(migrate(yaml.safe_load(f.read()))))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/storj/1.1.8/migrations/migrate_from_kubernetes", line 18, in migrate\n    old_wallets = config["storjConfig"].get("wallets", {})\n                  ~~~~~~^^^^^^^^^^^^^^^\nKeyError: \'storjConfig\'\n'
```

If guidance is provided as to how, I can try to read the configs from the Storj app that failed & the one that succeeded to understand why this migration is failing. 

It also appears that a similar error was reported on the forums for a different app: https://forums.truenas.com/t/truenas-24-10-rc-2-is-now-available/14819/21

**Comment by stavros-k** [comment]
Hello, this seems to be a more than 8 months old outdated app.
Due to a vastly different structure on the configuration it cannot be migrated.

**Comment by PocketSam** [comment]
Hi @nickles-lee . Did you find a way to run existing STORJ node? Using TrueNAS provided application requires to provide Auth Token, so it can't re-run existing node.
