### ISSUE TITLE
Photoprism fails to migrate

### ISSUE THREAD

**Issue by yichi-yang** [truenas/apps#623]
```
[2024/10/06 17:42:13] (DEBUG) app_migrations.migrate():231 - 'photoprism-2' app failed to migrate successfully:
Failed to migrate config: Failed to migrate config: Traceback (most recent call last):
  File "/mnt/.ix-apps/truenas_catalog/trains/stable/photoprism/1.1.11/migrations/migrate_from_kubernetes", line 57, in <module>
    print(yaml.dump(migrate(yaml.safe_load(f.read()))))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/truenas_catalog/trains/stable/photoprism/1.1.11/migrations/migrate_from_kubernetes", line 20, in migrate
    "site_url": config["photoprismConfig"]["siteURL"],
                ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'siteURL'
```
Perhaps another case of not upgrading to the latest version before migrating causing problem?

**Comment by stavros-k** [comment]
Correct, this is 8 months old addition :)
