### ISSUE TITLE
Minecraft app failed to migrate

### ISSUE THREAD

**Issue by bovine** [truenas/apps#651]
The log file `/var/log/app_migrations.log` contained this error after migrating to ElectricEel-24.10-RC.2

```
[2024/10/10 23:51:19] (DEBUG) app_migrations.migrate():231 - 'minecraft' app failed to migrate successfully: 'Failed to create app: [EFAULT] Failed to render compose templates: Traceback (most recent call last):
  File "/usr/bin/apps_render_app", line 33, in <module>
    sys.exit(load_entry_point(\'apps-validation==0.1\', \'console_scripts\', \'apps_render_app\')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main
    render_templates_from_path(args.path, args.values)
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path
    rendered_data = render_templates(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates
    ).render({\'ix_lib\': template_libs, \'values\': test_values})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/.ix-apps/app_configs/minecraft/versions/1.11.14/templates/docker-compose.yaml", line 73, in top-level template code
    {% if values.minecraft.ops and app_env.update({"OPS": join(values.minecraft.ops, ",")}) %}{% endif %}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 86, in from_obj
    if hasattr(obj, "jinja_pass_arg"):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: \'join\' is undefined
'
```

**Comment by bovine** [comment]
https://github.com/truenas/apps/blob/b76642467d2f7ba184c283027293c0386db377b8/ix-dev/community/minecraft/templates/docker-compose.yaml#L73

**Comment by ejytsu** [comment]
> https://github.com/truenas/apps/blob/b76642467d2f7ba184c283027293c0386db377b8/ix-dev/community/minecraft/templates/docker-compose.yaml#L73
> 
> Should that be something like:
> 
> ```
> {% if values.minecraft.ops and app_env.update({"OPS": values.minecraft.ops | join(",")}) %}{% endif %} 
> ```

Edited `/mnt/.ix-apps/truenas_catalog/trains/community/minecraft/1.11.14/templates/docker-compose.yaml` 

```
    {% if values.minecraft.ops and app_env.update({"OPS": values.minecraft.ops | join(",")}) %}{% endif %}
    {% if values.minecraft.whitelist and app_env.update({"WHITELIST": values.minecraft.whitelist | join(",")}) %}{% endif %}
```

Ran midclt call -job k8s_to_docker.migrate <<POOLNAME>>

Minecraft back up and running
