### ISSUE TITLE
NextCloud failed to migrate from kubernets

### ISSUE THREAD

**Issue by djpremier** [truenas/apps#709]
Hi,

Yesterday I migrated my server from Dragonfish (24.01) to ElectricEel (24.10 RC) and received the error log below, I hope it can help identify any possible problem in the migration script, if you need more information I am available.

`[2024/10/26 14:01:36] (DEBUG) app_migrations.migrate():231 - 'nextcloud' app failed to migrate successfully: 'Failed to migrate config: Failed to migrate config: Traceback (most recent call last):\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/nextcloud/1.3.23/migrations/migrate_from_kubernetes", line 91, in <module>\n    print(yaml.dump(migrate(yaml.safe_load(f.read()))))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/nextcloud/1.3.23/migrations/migrate_from_kubernetes", line 21, in migrate\n    "admin_user": config["ncConfig"]["adminUser"],\n                  ~~~~~~^^^^^^^^^^^^\nKeyError: \'ncConfig\'\n'`

**Comment by stavros-k** [comment]
Hello, it seems that your nextcloud installation was at least 6 months old. And the configuration has vastly changed since then.

In this case, It cannot be migrated automatically.

**Comment by daseinzigwahreuwe** [comment]
This issue is closed, but I got exaclty the same one. 
My nextcloud was the latest version available: 30.0.5 on dragonfish

This is the result:
[2025/02/14 23:38:34] (DEBUG) app_migrations.migrate():250 - Migration details for 'system-update--2025-02-14_22:35:25' backup on 'AppsPool' pool
[2025/02/14 23:38:34] (DEBUG) app_migrations.migrate():256 - 'nextcloud' app failed to migrate successfully: 'Failed to migrate config: Failed to migrate config: Traceback (most recent call last):\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/nextcloud/1.6.3/migrations/migrate_from_kubernetes", line 91, in <module>\n    print(yaml.dump(migrate(yaml.safe_load(f.read()))))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/nextcloud/1.6.3/migrations/migrate_from_kubernetes", line 21, in migrate\n    "admin_user": config["ncConfig"]["adminUser"],\n                  ~~~~~~^^^^^^^^^^^^\nKeyError: \'ncConfig\'\n'

running midclt call -job k8s_to_docker.migrate AppsPool does not help. Leads to the same issue.

Any Input what to do? Already tried a lot of things. But I do not have enough understanding to get to the point what could be wrong.
Cannot be outdated Nextcloud. At least dragonfish did not have any update available.

**Comment by stavros-k** [comment]
If you are positive that you had the latest version, then its possible that you were hit by this issue.
There is a manual fix for that in this ticket.
https://ixsystems.atlassian.net/browse/TNCHARTS-1570?focusedCommentId=296223
