### ISSUE TITLE
WG-Easy failed to migrate from kubernetes

### ISSUE THREAD

**Issue by djpremier** [truenas/apps#710]
Hi,

Yesterday I migrated my server from Dragonfish (24.01) to ElectricEel (24.10 RC) and received the error log below, I hope it can help identify any possible problem in the migration script, if you need more information I am available.

`[2024/10/26 14:01:36] (DEBUG) app_migrations.migrate():231 - 'wg-easy' app failed to migrate successfully: 'Failed to migrate config: Failed to migrate config: Traceback (most recent call last):\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/wg-easy/1.0.20/migrations/migrate_from_kubernetes", line 55, in <module>\n    print(yaml.dump(migrate(yaml.safe_load(f.read()))))\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/mnt/.ix-apps/truenas_catalog/trains/stable/wg-easy/1.0.20/migrations/migrate_from_kubernetes", line 20, in migrate\n    "external_port": config["wgConfig"]["externalPort"],\n                     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^\nKeyError: \'externalPort\'\n'`

**Comment by stavros-k** [comment]
Hello, looks like this app haven't been updated for the past 6 months at least.

In this case, the app cannot be automatically updated.
