### ISSUE TITLE
Frigate failing to start with GPU on ElectricEel

### ISSUE THREAD

**Issue by JamesTaylor92** [truenas/apps#732]
Upgraded to Electric Eel from previous stable version. App migrated okay but crashes on startup, doesn't appear to detect the Nvidia GPU.

```
Application Name:frigateContainer ID:e48e1bf4855d1028288ce0270d656e2be533a01802ff622271efe011e4f05fb0
2024-10-29 20:07:58.114403+00:00s6-rc: info: service s6rc-fdholder: starting
2024-10-29 20:07:58.114532+00:00s6-rc: info: service s6rc-oneshot-runner: starting
2024-10-29 20:07:58.116749+00:00s6-rc: info: service s6rc-oneshot-runner successfully started
2024-10-29 20:07:58.116840+00:00s6-rc: info: service fix-attrs: starting
2024-10-29 20:07:58.117695+00:00s6-rc: info: service s6rc-fdholder successfully started
2024-10-29 20:07:58.120639+00:00s6-rc: info: service fix-attrs successfully started
2024-10-29 20:07:58.120807+00:00s6-rc: info: service legacy-cont-init: starting
2024-10-29 20:07:58.124317+00:00s6-rc: info: service legacy-cont-init successfully started
2024-10-29 20:07:58.124370+00:00s6-rc: info: service trt-model-prepare: starting
2024-10-29 20:07:58.124498+00:00s6-rc: info: service log-prepare: starting
2024-10-29 20:07:58.130834+00:00s6-rc: info: service log-prepare successfully started
2024-10-29 20:07:58.130966+00:00s6-rc: info: service nginx-log: starting
2024-10-29 20:07:58.131101+00:00s6-rc: info: service go2rtc-log: starting
2024-10-29 20:07:58.131167+00:00s6-rc: info: service frigate-log: starting
2024-10-29 20:07:58.131303+00:00s6-rc: info: service certsync-log: starting
2024-10-29 20:07:58.132720+00:00s6-rc: info: service go2rtc-log successfully started
2024-10-29 20:07:58.132815+00:00s6-rc: info: service go2rtc: starting
2024-10-29 20:07:58.133001+00:00s6-rc: info: service nginx-log successfully started
2024-10-29 20:07:58.133205+00:00s6-rc: info: service frigate-log successfully started
2024-10-29 20:07:58.133428+00:00s6-rc: info: service certsync-log successfully started
2024-10-29 20:07:58.134534+00:00s6-rc: info: service go2rtc successfully started
2024-10-29 20:07:58.134876+00:00s6-rc: info: service go2rtc-healthcheck: starting
2024-10-29 20:07:58.135576+00:00No models to convert.
2024-10-29 20:07:58.136098+00:00s6-rc: info: service trt-model-prepare successfully started
2024-10-29 20:07:58.136548+00:00s6-rc: info: service frigate: starting
2024-10-29 20:07:58.136882+00:00s6-rc: info: service go2rtc-healthcheck successfully started
2024-10-29 20:07:58.139274+00:00s6-rc: info: service frigate successfully started
2024-10-29 20:07:58.139304+00:00s6-rc: info: service nginx: starting
2024-10-29 20:07:58.141895+00:002024-10-29 20:07:58.141743192  [INFO] Preparing Frigate...
2024-10-29 20:07:58.142331+00:002024-10-29 20:07:58.142267094  [INFO] Starting NGINX...
2024-10-29 20:07:58.142671+00:002024-10-29 20:07:58.142570896  [INFO] Preparing new go2rtc config...
2024-10-29 20:07:58.147105+00:002024-10-29 20:07:58.147025853  [INFO] No TLS certificate found. Generating a self signed certificate...
2024-10-29 20:07:58.149798+00:002024-10-29 20:07:58.149663876  [INFO] Starting Frigate...
2024-10-29 20:07:58.490407+00:002024-10-29 20:07:58.490324133  [INFO] Starting go2rtc...
2024-10-29 20:07:58.661942+00:002024-10-29 20:07:58.661863800  20:07:58.661 INF go2rtc platform=linux/amd64 revision=b2399f3 version=1.9.2
2024-10-29 20:07:58.661970+00:002024-10-29 20:07:58.661881766  20:07:58.661 INF config path=/dev/shm/go2rtc.yaml
2024-10-29 20:07:58.662484+00:002024-10-29 20:07:58.662414656  20:07:58.662 INF [api] listen addr=:1984
2024-10-29 20:07:58.662526+00:002024-10-29 20:07:58.662477920  20:07:58.662 INF [rtsp] listen addr=:8554
2024-10-29 20:07:58.662705+00:002024-10-29 20:07:58.662663979  20:07:58.662 INF [webrtc] listen addr=:8555/tcp
2024-10-29 20:07:59.578829+00:002024-10-29 20:07:59.578720115  [2024-10-29 20:07:59] frigate.app                    INFO    : Starting Frigate (0.14.1-f4f3cfa)
2024-10-29 20:07:59.578858+00:002024-10-29 20:07:59.578786057  [2024-10-29 20:07:59] frigate.util.config            INFO    : Checking if frigate config needs migration...
2024-10-29 20:07:59.603789+00:002024-10-29 20:07:59.603717707  [2024-10-29 20:07:59] frigate.util.config            INFO    : frigate config does not need migration...
2024-10-29 20:07:59.697866+00:00s6-rc: info: service nginx successfully started
2024-10-29 20:07:59.698181+00:00s6-rc: info: service certsync: starting
2024-10-29 20:07:59.704343+00:00s6-rc: info: service certsync successfully started
2024-10-29 20:07:59.704784+00:00s6-rc: info: service legacy-services: starting
2024-10-29 20:07:59.714737+00:002024-10-29 20:07:59.714341123  [INFO] Starting certsync...
2024-10-29 20:07:59.725379+00:00s6-rc: info: service legacy-services successfully started
2024-10-29 20:08:38.655790+00:002024-10-29 20:08:38.655700384  [2024-10-29 20:08:38] peewee_migrate.logs            INFO    : Starting migrations
2024-10-29 20:08:38.656220+00:002024-10-29 20:08:38.656124142  [2024-10-29 20:08:38] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-10-29 20:08:38.746253+00:002024-10-29 20:08:38.746161287  [2024-10-29 20:08:38] frigate.app                    INFO    : Recording process started: 436
2024-10-29 20:08:38.746281+00:002024-10-29 20:08:38.746224803  [2024-10-29 20:08:38] frigate.app                    INFO    : Recording process started: 438
2024-10-29 20:08:38.748652+00:002024-10-29 20:08:38.748593140  [2024-10-29 20:08:38] frigate.app                    INFO    : go2rtc process pid: 109
2024-10-29 20:08:38.767235+00:002024-10-29 20:08:38.767136926  Process detector:tensorrt:
2024-10-29 20:08:38.767274+00:002024-10-29 20:08:38.767158694  [2024-10-29 20:08:38] detector.tensorrt              INFO    : Starting detection process: 464
2024-10-29 20:08:38.767961+00:002024-10-29 20:08:38.767915853  Traceback (most recent call last):
2024-10-29 20:08:38.767993+00:002024-10-29 20:08:38.767950607    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-10-29 20:08:38.768005+00:002024-10-29 20:08:38.767952554      self.run()
2024-10-29 20:08:38.768013+00:002024-10-29 20:08:38.767957879    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-10-29 20:08:38.768027+00:002024-10-29 20:08:38.767960923      self._target(*self._args, **self._kwargs)
2024-10-29 20:08:38.768037+00:002024-10-29 20:08:38.767973801    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-10-29 20:08:38.768046+00:002024-10-29 20:08:38.767975566      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-10-29 20:08:38.768058+00:002024-10-29 20:08:38.767977383    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-10-29 20:08:38.768067+00:002024-10-29 20:08:38.767978796      self.detect_api = create_detector(detector_config)
2024-10-29 20:08:38.768075+00:002024-10-29 20:08:38.767980250    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-10-29 20:08:38.768086+00:002024-10-29 20:08:38.767994633      return api(detector_config)
2024-10-29 20:08:38.768095+00:002024-10-29 20:08:38.767996066    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 229, in __init__
2024-10-29 20:08:38.768103+00:002024-10-29 20:08:38.767997860      (cuda_err,) = cuda.cuInit(0)
2024-10-29 20:08:38.768111+00:002024-10-29 20:08:38.767999336    File "cuda/cuda.pyx", line 11325, in cuda.cuda.cuInit
2024-10-29 20:08:38.768124+00:002024-10-29 20:08:38.768001002    File "cuda/ccuda.pyx", line 17, in cuda.ccuda.cuInit
2024-10-29 20:08:38.768135+00:002024-10-29 20:08:38.768014506    File "cuda/_cuda/ccuda.pyx", line 2350, in cuda._cuda.ccuda._cuInit
2024-10-29 20:08:38.768143+00:002024-10-29 20:08:38.768016284    File "cuda/_cuda/ccuda.pyx", line 424, in cuda._cuda.ccuda.cuPythonInit
2024-10-29 20:08:38.768156+00:002024-10-29 20:08:38.768017725  RuntimeError: Failed to dlopen libcuda.so
2024-10-29 20:08:38.768164+00:002024-10-29 20:08:38.768040254  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f60169663a0>
2024-10-29 20:08:38.768172+00:002024-10-29 20:08:38.768050723  Traceback (most recent call last):
2024-10-29 20:08:38.768185+00:002024-10-29 20:08:38.768052381    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 265, in __del__
2024-10-29 20:08:38.768218+00:002024-10-29 20:08:38.768175969      if self.outputs is not None:
2024-10-29 20:08:38.768235+00:002024-10-29 20:08:38.768177689  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2024-10-29 20:08:38.768292+00:002024-10-29 20:08:38.768251429  [2024-10-29 20:08:38] frigate.app                    INFO    : Output process started: 466
2024-10-29 20:08:38.852131+00:002024-10-29 20:08:38.852009849  [2024-10-29 20:08:38] frigate.app                    INFO    : Camera processor started for rear: 506
2024-10-29 20:08:38.861725+00:002024-10-29 20:08:38.861656176  [2024-10-29 20:08:38] frigate.app                    INFO    : Camera processor started for drive: 513
2024-10-29 20:08:38.861822+00:002024-10-29 20:08:38.861788334  [2024-10-29 20:08:38] frigate.app                    INFO    : Camera processor started for front: 516
2024-10-29 20:08:38.872011+00:002024-10-29 20:08:38.871868489  [2024-10-29 20:08:38] frigate.app                    INFO    : Camera processor started for garage: 524
2024-10-29 20:08:38.872064+00:002024-10-29 20:08:38.871929607  [2024-10-29 20:08:38] frigate.app                    INFO    : Camera processor started for garden: 532
2024-10-29 20:08:38.878114+00:002024-10-29 20:08:38.878038302  [2024-10-29 20:08:38] frigate.app                    INFO    : Capture process started for rear: 543
2024-10-29 20:08:38.884557+00:002024-10-29 20:08:38.884464422  [2024-10-29 20:08:38] frigate.app                    INFO    : Capture process started for drive: 548
2024-10-29 20:08:38.890638+00:002024-10-29 20:08:38.890535234  [2024-10-29 20:08:38] frigate.app                    INFO    : Capture process started for front: 554
2024-10-29 20:08:38.896763+00:002024-10-29 20:08:38.896659462  [2024-10-29 20:08:38] frigate.app                    INFO    : Capture process started for garage: 565
2024-10-29 20:08:38.906456+00:002024-10-29 20:08:38.905883634  [2024-10-29 20:08:38] frigate.app                    INFO    : Capture process started for garden: 572
2024-10-29 20:08:43.363776+00:002024-10-29 20:08:43.363700265  127.0.0.1 - - [29/Oct/2024:20:08:43 +0000] "GET /api HTTP/1.1" 301 169 "-" "curl/7.74.0" "-"
2024-10-29 20:08:44.421254+00:002024-10-29 20:08:44.421028603  [2024-10-29 20:08:44] frigate.video                  ERROR   : drive: Unable to read frames from ffmpeg process.
2024-10-29 20:08:44.422122+00:002024-10-29 20:08:44.421888976  [2024-10-29 20:08:44] frigate.video                  ERROR   : drive: ffmpeg process is not running. exiting capture thread...
2024-10-29 20:08:45.640010+00:002024-10-29 20:08:45.639738630  [2024-10-29 20:08:45] frigate.video                  ERROR   : front: Unable to read frames from ffmpeg process.
2024-10-29 20:08:45.640272+00:002024-10-29 20:08:45.640063736  [2024-10-29 20:08:45] frigate.video                  ERROR   : front: ffmpeg process is not running. exiting capture thread...
2024-10-29 20:08:46.673236+00:002024-10-29 20:08:46.672981197  [2024-10-29 20:08:46] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-10-29 20:08:46.673853+00:002024-10-29 20:08:46.673656967  [2024-10-29 20:08:46] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2024-10-29 20:08:48.021853+00:002024-10-29 20:08:48.021566429  [2024-10-29 20:08:48] frigate.video                  ERROR   : garden: Unable to read frames from ffmpeg process.
2024-10-29 20:08:48.022945+00:002024-10-29 20:08:48.022755517  [2024-10-29 20:08:48] frigate.video                  ERROR   : garden: ffmpeg process is not running. exiting capture thread...
2024-10-29 20:08:48.458116+00:002024-10-29 20:08:48.457878056  [2024-10-29 20:08:48] frigate.video                  ERROR   : rear: Unable to read frames from ffmpeg process.
2024-10-29 20:08:48.458365+00:002024-10-29 20:08:48.458187414  [2024-10-29 20:08:48] frigate.video                  ERROR   : rear: ffmpeg process is not running. exiting capture thread...
2024-10-29 20:08:58.931096+00:002024-10-29 20:08:58.930985486  [2024-10-29 20:08:58] watchdog.drive                 ERROR   : Ffmpeg process crashed unexpectedly for drive.
2024-10-29 20:08:58.931135+00:002024-10-29 20:08:58.930988893  [2024-10-29 20:08:58] watchdog.drive                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-10-29 20:08:58.931154+00:002024-10-29 20:08:58.930990943  [2024-10-29 20:08:58] ffmpeg.drive.detect            ERROR   : [AVHWDeviceContext @ 0x5591259a2340] Cannot load libcuda.so.1
2024-10-29 20:08:58.931168+00:002024-10-29 20:08:58.930992945  [2024-10-29 20:08:58] ffmpeg.drive.detect            ERROR   : [AVHWDeviceContext @ 0x5591259a2340] Could not dynamically load CUDA
2024-10-29 20:08:58.931176+00:002024-10-29 20:08:58.930994686  [2024-10-29 20:08:58] ffmpeg.drive.detect            ERROR   : Device creation failed: -1.
2024-10-29 20:08:58.931184+00:002024-10-29 20:08:58.930998684  [2024-10-29 20:08:58] ffmpeg.drive.detect            ERROR   : [h264 @ 0x5591259accc0] No device available for decoder: device type cuda needed for codec h264.
2024-10-29 20:08:58.931195+00:002024-10-29 20:08:58.931000692  [2024-10-29 20:08:58] ffmpeg.drive.detect            ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
```

**Comment by stavros-k** [comment]
What does `nvidia-smi` show if you run it inside the frigate container?
Can you also share the result of `env | grep NVIDIA` (also run in the container)

**Comment by JamesTaylor92** [comment]
> What does `nvidia-smi` show if you run it inside the frigate container? Can you also share the result of `env | grep NVIDIA` (also run in the container)

Looks like nvidia-smi isn't part of the container image. No env vars containing "nvidia".

lspci from within the container can see the GPU however.
`root@c56214106bb2:/opt/frigate# lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3080] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GA102 High Definition Audio Controller (rev a1)`

**Comment by JamesTaylor92** [comment]
I made some progress after more closely inspecting the release notes that might be useful for someone else.

As of Electric Eel Nvidia drivers are no longer included by default. You can enable them from Apps -> Configuration -> Settings -> Check Install Nvidia Drivers

Editing the Frigate app, the interface changes slightly to allow you to select the GPU. This however fails with an error for me:
```[EFAULT] Failed to render compose templates: base_v1_1_4.utils.TemplateException: Expected [uuid] to be set for GPU inslot [0000:01:00.0] in [nvidia_gpu_selection]

 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 287, in do_update
    app = self.update_internal(job, app, data, trigger_compose=app['state'] != 'STOPPED')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 317, in update_internal
    update_app_config(app_name, app['version'], new_values, custom_app=app['custom_app'])
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 59, in update_app_config
    render_compose_templates(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 50, in render_compose_templates
    raise CallError(f'Failed to render compose templates: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed to render compose templates: base_v1_1_4.utils.TemplateException: Expected [uuid] to be set for GPU inslot [0000:01:00.0] in [nvidia_gpu_selection]
```

**Comment by stavros-k** [comment]
I see, yes new installs should work just fine. Please follow this ticket for further updates on this
https://ixsystems.atlassian.net/browse/NAS-132086

Thanks!
