### ISSUE TITLE
Installing Paperless-ngx on 24.10.0 fails when postgres volume is set to host path

### ISSUE THREAD

**Issue by S1lencio** [truenas/apps#733]
The Paperless-ngx app fails to install when setting "Paperless-ngx Postgres Data Storage" to host path. The installation completes normally when using ixVolume. All other paths can be set to host path. This issue occurs even on newly generated datasets with no modification, using preset "App" or "Generic".

It also installs but fails to start with a too "complicated" redis password. Using (generated examples) `FyX48Mx9qy` would work, but `%!bV*Pm^%TKeJaLaUtnUn#568bRsvZP959V97Asv` would cause a part of the password to be used as the port.

Here is the installation error when using host path for postgres data storage:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 203, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 248, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 241, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 57, in compose_action
    raise CallError(
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'paperless-ngx' app, please check /var/log/app_lifecycle.log for more details
```

`[EFAULT] Failed 'up' action for 'paperless-ngx' app, please check /var/log/app_lifecycle.log for more details`

**Comment by S1lencio** [comment]
After encountering the same issue with Immich, I found [this](https://github.com/truenas/apps/issues/636) issue with a way to resolve it.

**Comment by stavros-k** [comment]
Hello, yes postgres need `999:999` permissions

**Comment by stavros-k** [comment]
Most likely the `%` causing the issue here. 
It should be fixed in v2-library, but will take a minute to update all apps to use that library.
