### ISSUE TITLE
Cannot start Jellyfin after updating to 24.10, report unhealthy by docker

### ISSUE THREAD

**Issue by Jade9nan** [truenas/apps#735]
It seems Jellyfin failed to listen to 8096 port?

Here is the log
```zsh
root@truenas [15:35:44] [~] 
-> # docker ps                                                                                    
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS                            PORTS                     NAMES
6e4b10b4a797   jellyfin/jellyfin:10.10.0         "/jellyfin/jellyfin"     4 minutes ago   Up 4 minutes (health: starting)   0.0.0.0:30013->8096/tcp   ix-jellyfin-jellyfin-1
af1dfeb3b335   metatube/metatube-server:latest   "/metatube-server -d…"   7 minutes ago   Up 7 minutes                      0.0.0.0:30069->8080/tcp   ix-metatube-metatube-1
root@truenas [15:39:20] [~] 
-> # docker inspect --format "{{json .State.Health }}" 6e4b10b4a797                               
{"Status":"unhealthy","FailingStreak":30,"Log":[{"Start":"2024-10-30T15:38:56.847838582+09:00","End":"2024-10-30T15:38:56.932312496+09:00","ExitCode":7,"Output":"curl: (7) Failed to connect to 127.0.0.1 port 8096 after 0 ms: Couldn't connect to server\n"},{"Start":"2024-10-30T15:39:06.933552219+09:00","End":"2024-10-30T15:39:07.013964296+09:00","ExitCode":7,"Output":"curl: (7) Failed to connect to 127.0.0.1 port 8096 after 0 ms: Couldn't connect to server\n"},{"Start":"2024-10-30T15:39:17.014752813+09:00","End":"2024-10-30T15:39:17.10493234+09:00","ExitCode":7,"Output":"curl: (7) Failed to connect to 127.0.0.1 port 8096 after 0 ms: Couldn't connect to server\n"},{"Start":"2024-10-30T15:39:27.105418091+09:00","End":"2024-10-30T15:39:27.203960734+09:00","ExitCode":7,"Output":"curl: (7) Failed to connect to 127.0.0.1 port 8096 after 0 ms: Couldn't connect to server\n"},{"Start":"2024-10-30T15:39:37.20501166+09:00","End":"2024-10-30T15:39:37.291836825+09:00","ExitCode":7,"Output":"curl: (7) Failed to connect to 127.0.0.1 port 8096 after 0 ms: Couldn't connect to server\n"}]}

root@truenas [15:48:48] [~] 
-> # docker logs -f 967c655d88e7                                                                  
[15:41:14] [INF] [1] Main: Jellyfin version: 10.10.0
[15:41:14] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]"]
[15:41:14] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[15:41:14] [INF] [1] Main: Operating system: Debian GNU/Linux 12 (bookworm)
[15:41:14] [INF] [1] Main: Architecture: X64
[15:41:14] [INF] [1] Main: 64-Bit Process: True
[15:41:14] [INF] [1] Main: User Interactive: True
[15:41:14] [INF] [1] Main: Processor count: 4
[15:41:14] [INF] [1] Main: Program data path: /config
[15:41:14] [INF] [1] Main: Log directory path: /config/log
[15:41:14] [INF] [1] Main: Config directory path: /config/config
[15:41:14] [INF] [1] Main: Cache path: /cache
[15:41:14] [INF] [1] Main: Temp directory path: /tmp/jellyfin
[15:41:14] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[15:41:14] [INF] [1] Main: Application directory: /jellyfin/
[15:41:14] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[15:41:14] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.AniDB, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/AniDB_9.0.0.0/Jellyfin.Plugin.AniDB.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Bangumi, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Jellyfin.Plugin.Bangumi.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Fastenshtein, Version=1.0.0.8, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/Fastenshtein.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly AnitomySharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Bangumi_1.6.2.0/AnitomySharp.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin 1.7.0.0 of Bangumi 
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Rssdp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Rssdp.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly MetaTube, Version=2024.612.210.0, Culture=neutral, PublicKeyToken=null from /config/plugins/MetaTube_2024.612.210.0/MetaTube.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /config/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /config/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /config/plugins/Reports_17.0.0.0/ClosedXML.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /config/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /config/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
[15:41:14] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.16.2.2"]
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[15:41:14] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AniDB 9.0.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Bangumi 1.6.2.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: DLNA 3.0.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MetaTube 2024.612.210.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Playback Reporting 15.0.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Reports 17.0.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.10.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.10.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.10.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.10.0.0
[15:53:57] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.10.0.0
[15:53:57] [ERR] [1] Main: Kestrel failed to start! This is most likely due to an invalid address or port bind - correct your bind configuration in network.xml and try again
[15:53:57] [FTL] [1] Main: Error while starting server
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.UserItemData> MediaBrowser.Controller.Library.IUserDataManager.GetAllUserData(System.Guid)'.
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler.GetPlaybackHistory(Guid userId)
   at Jellyfin.Plugin.Bangumi.PlaybackScrobbler..ctor(IUserManager userManager, IUserDataManager userDataManager, ILocalizationManager localizationManager, OAuthStore store, BangumiApi api, ILogger`1 log)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[15:53:57] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[15:53:57] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[15:53:57] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzArtistProvider
[15:53:57] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[15:53:57] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager


```

And the rendered docker-compose.yaml
from `/mnt/.ix-apps/app_configs/jellyfin/versions/1.0.26/templates/rendered/docker-compose.yaml`
```yaml
services:
  jellyfin:
    user: 568:568
    image: jellyfin/jellyfin:10.10.0
    restart: unless-stopped
    deploy:
      resources: {"limits": {"cpus": "4", "memory": "8192M"}}
    devices: ["/dev/dri:/dev/dri"]
    
    group_add:
      - 44  # video
      - 107 # render
    
    
    depends_on:
      permissions:
        condition: service_completed_successfully
    
    
    cap_drop: ["ALL"]
    security_opt: ["no-new-privileges"]
    
    
    healthcheck: {"interval": "10s", "retries": 30, "start_period": "10s", "test": "curl --silent --output /dev/null --show-error --fail  http://127.0.0.1:8096/health", "timeout": "5s"}
    
    
    environment: {"GID": "568", "GROUP_ID": "568", "NVIDIA_VISIBLE_DEVICES": "void", "PGID": "568", "PUID": "568", "TZ": "Asia/Tokyo", "UID": "568", "USER_ID": "568"}
    
    ports:
      - {"host_ip": "0.0.0.0", "mode": "ingress", "protocol": "tcp", "published": 30013, "target": 8096}
    
    volumes: [{"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/config", "target": "/config", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/cache", "target": "/cache", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/transcodes", "target": "/config/transcodes", "type": "bind"}, {"read_only": false, "source": "tmp", "target": "/tmp", "type": "volume", "volume": {"nocopy": false}}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/tank/bt", "target": "/bt", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/tank/app-settings/font", "target": "/font", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/usr/share/fonts", "target": "/usr/share/fonts", "type": "bind"}]
  
  permissions: {"command": ["\nfunction process_dir() {\n    local dir=$$1\n    local mode=$$2\n    local uid=$$3\n    local gid=$$4\n    local chmod=$$5\n    local is_temporary=$$6\n\n    local fix_owner=\"false\"\n    local fix_perms=\"false\"\n\n    if [ -z \"$$dir\" ]; then\n        echo \"Path is empty, skipping...\"\n        return 0\n    fi\n\n    if [ ! -d \"$$dir\" ]; then\n        echo \"Path [$$dir] does is not a directory, skipping...\"\n        return 0\n    fi\n\n    if [ \"$$is_temporary\" = \"true\" ]; then\n        echo \"Path [$$dir] is a temporary directory, ensuring it is empty...\"\n        # Exclude the safe directory, where we can use to mount files temporarily\n        find \"$$dir\" -mindepth 1 -maxdepth 1 ! -name \"ix-safe\" -exec rm -rf {} +\n    fi\n\n    if [ \"$$is_temporary\" = \"false\" ] \u0026\u0026 [ -n \"$$(ls -A $$dir)\" ]; then\n        echo \"Path [$$dir] is not empty, skipping...\"\n        return 0\n    fi\n\n    echo \"Current Ownership and Permissions on [$$dir]:\"\n    echo \"chown: $$(stat -c \"%u %g\" \"$$dir\")\"\n    echo \"chmod: $$(stat -c \"%a\" \"$$dir\")\"\n\n    if [ \"$$mode\" = \"always\" ]; then\n        fix_owner=\"true\"\n        fix_perms=\"true\"\n    fi\n\n    if [ \"$$mode\" = \"check\" ]; then\n        if [ $$(stat -c %u \"$$dir\") -eq $$uid ] \u0026\u0026 [ $$(stat -c %g \"$$dir\") -eq $$gid ]; then\n            echo \"Ownership is correct. Skipping...\"\n            fix_owner=\"false\"\n        else\n            echo \"Ownership is incorrect. Fixing...\"\n            fix_owner=\"true\"\n        fi\n\n        if [ \"$$chmod\" = \"false\" ]; then\n            echo \"Skipping permissions check, chmod is false\"\n        elif [ -n \"$$chmod\" ]; then\n            if [ $$(stat -c %a \"$$dir\") -eq $$chmod ]; then\n                echo \"Permissions are correct. Skipping...\"\n                fix_perms=\"false\"\n            else\n                echo \"Permissions are incorrect. Fixing...\"\n                fix_perms=\"true\"\n            fi\n        fi\n    fi\n\n    if [ \"$$fix_owner\" = \"true\" ]; then\n        echo \"Changing ownership to $$uid:$$gid on: [$$dir]\"\n        chown -R \"$$uid:$$gid\" \"$$dir\"\n        echo \"Finished changing ownership\"\n        echo \"Ownership after changes:\"\n        stat -c \"%u %g\" \"$$dir\"\n    fi\n\n    if [ -n \"$$chmod\" ] \u0026\u0026 [ \"$$fix_perms\" = \"true\" ]; then\n        echo \"Changing permissions to $$chmod on: [$$dir]\"\n        chmod -R \"$$chmod\" \"$$dir\"\n        echo \"Finished changing permissions\"\n        echo \"Permissions after changes:\"\n        stat -c \"%a\" \"$$dir\"\n    fi\n}\n\nprocess_dir /mnt/jellyfin/config check 568 568 false false\nprocess_dir /mnt/jellyfin/cache check 568 568 false false\nprocess_dir /mnt/jellyfin/transcodes check 568 568 false false\nprocess_dir /mnt/jellyfin/tmp check 568 568 false true"], "deploy": {"resources": {"limits": {"cpus": "1.0", "memory": "512m"}}}, "entrypoint": ["bash", "-c"], "image": "bash", "user": "root", "volumes": [{"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/config", "target": "/mnt/jellyfin/config", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/cache", "target": "/mnt/jellyfin/cache", "type": "bind"}, {"bind": {"create_host_path": false, "propagation": "rprivate"}, "read_only": false, "source": "/mnt/.ix-apps/app_mounts/jellyfin/transcodes", "target": "/mnt/jellyfin/transcodes", "type": "bind"}, {"read_only": false, "source": "tmp", "target": "/mnt/jellyfin/tmp", "type": "volume", "volume": {"nocopy": false}}]}
  


volumes: {"tmp": {}}


x-portals: [{"host": "0.0.0.0", "name": "Web UI", "path": "/", "port": 30013, "scheme": "http"}]
x-notes: "# Welcome to TrueNAS SCALE\n\nThank you for installing Jellyfin!\n\n\n\n\n## Documentation\n\nDocumentation for Jellyfin can be found at https://www.truenas.com/docs.\n\n## Bug reports\n\nIf you find a bug in this app, please file an issue at\nhttps://ixsystems.atlassian.net or https://github.com/truenas/apps\n\n## Feature requests or improvements\n\nIf you find a feature request for this app, please file an issue at\nhttps://ixsystems.atlassian.net or https://github.com/truenas/apps\n"#   
```

**Comment by Jade9nan** [comment]
Sorry, finally I found it's the reason of Bangumi plugin of Jellyfin, now it's solved.
