### ISSUE TITLE
immich upload and library mounts should be combined

### ISSUE THREAD

**Issue by NicholasFlamy** [truenas/apps#893]
https://immich.app/docs/guides/custom-locations/
![Screenshot 2024-11-11 173501](https://github.com/user-attachments/assets/6007a9e0-af8e-4e9c-a677-b1362be3009c)
The upload and library mounts should be combined to prevent excessive wear.

_Originally posted by @NicholasFlamy in https://github.com/truenas/apps/issues/411#issuecomment-2469203641_

**Comment by NicholasFlamy** [comment]
I have a suggestion to add, By default have the mounts unchecked and go to default best practices of being part of the library mount and if someone wants to specify they can hit the checkbox to show the mount option, this would also work for migrations.

I could PR this, but I've never done the migrations part.

**Comment by jondycz** [comment]
I second this. This is indeed necessary when dealing with large number of file uploads. Doesn't really make sense to separate as uploaded files are automatically moved from the upload folder to the library folder anyway.

**Comment by kidroca** [comment]
> I have a suggestion to add, By default have the mounts unchecked and go to default best practices of being part of the library mount

This should be the default similar to when running Immich via docker-compose file

**Comment by kidroca** [comment]
Would a workaround like creating `library` and `upload` as plain folders in a Dataset and setting those as host path in App config work? 
Or because they are defined as separate mounts it would still copy and delete the file?

**Comment by stavros-k** [comment]
Okay, a toggle is being added, where existing installations will be migrate to have this enabled (old storage config).
New installs will have it by default disabled (and prevented from installing if its true).

Few months later the toggle will be completed removed and all installs should use the new storage config (1 bind mount).

Existing installs can edit the app after upgrade and use the new consolidated storage config. (You will have to move the data to a single dataset manually and point the storage to the new dataset).

Users that _still__ want to use separate mounts, they will be able to use the additional storages to mount on top of the single bind mount as normal.

**Comment by Adrian-Grimm** [comment]
@stavros-k : please think again about this change... some of us prever to differ between SSD and HDD storage.

e.g. my case:

HDD based storage for huge data (8TB) like: video, uploads, library
SSD only storage for: all of the rest 

would be nice to at least be able to differ also for thumbs and profile data.

**Comment by grozan** [comment]
the instructions in the PR files look incorrect.
In the new data folder I had to rename the `uploads` folder to `upload` (singular), otherwise the application crashes with 

```
[Nest] 7  - 06/14/2025, 4:04:42 PM     LOG [Microservices:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
[Nest] 7  - 06/14/2025, 4:04:42 PM   ERROR [Microservices:StorageService] Failed to read upload/upload/.immich: Error: ENOENT: no such file or directory, open 'upload/upload/.immich'
microservices worker error: Error: Failed to read "<UPLOAD_LOCATION>/upload/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information.", stack: Error: Failed to read "<UPLOAD_LOCATION>/upload/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information."
    at StorageService.verifyReadAccess (/usr/src/app/dist/services/storage.service.js:84:19)
    at async /usr/src/app/dist/services/storage.service.js:38:21
    at async /usr/src/app/dist/repositories/database.repository.js:377:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async /usr/src/app/dist/repositories/database.repository.js:374:13
microservices worker exited with code 1
```

**Comment by mainman94** [comment]
@grozan is correct. Can confirm it mus be upload instead of uploads .
You saved me. Thx 👍

**Comment by NicholasFlamy** [comment]
> Users that _still_ want to use separate mounts, they will be able to use the additional storages to mount on top of the single bind mount as normal.

This is good. When this change goes through, if I find the time, I'll try to update the immich TrueNAS install docs to inform users of this.

**Comment by schmitzkr** [comment]
> > Users that _still_ want to use separate mounts, they will be able to use the additional storages to mount on top of the single bind mount as normal.
> 
> This is good. When this change goes through, if I find the time, I'll try to update the immich TrueNAS install docs to inform users of this.

I only want separate ones for the thumbs and encoded videos.  I need those to be on faster drives to keep my users happy with the timeline performance. Do we just mount the thumbs data to UPLOAD_LOCATION/thumbs?

**Comment by stavros-k** [comment]
> would be nice to at least be able to differ also for thumbs and profile data.

It IS possible.
Just mount an additional storage like I mention in my comment.

ie to have thumbs in another pool/dataset/directory, just mount an additional storage here 
`/usr/src/app/upload/thumbs`

**Comment by schmitzkr** [comment]
> > would be nice to at least be able to differ also for thumbs and profile data.
> 
> It IS possible. Just mount an additional storage like I mention in my comment.
> 
> ie to have thumbs in another pool/dataset/directory, just mount an additional storage here `/usr/src/app/upload/thumbs`

yes thank you! 
my /thumbs and /encoded-videos are on nvme and I added additional storage hostpaths at 
/usr/src/app/upload/encoded-video
/usr/src/app/upload/thumbs
I set the data directory to my immich-userdate hostpath which has all other directories
immich started up without issue.

**Comment by Adrian-Grimm** [comment]
@stavros-k 
my backups folder was a ixVolume previosly ... seems to be now the problem why my installation does not start again... 
any help?

```
2025-06-18 18:41:28.035902+00:00[32m[Nest] 7  - [39m06/18/2025, 8:41:28 PM [32m    LOG[39m [33m[Microservices:StorageService][39m [32mVerifying system mount folder checks, current state: {"mountFiles":true,"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}[39m
2025-06-18 18:41:28.037850+00:00[31m[Nest] 7  - [39m06/18/2025, 8:41:28 PM [31m  ERROR[39m [33m[Microservices:StorageService][39m [31mFailed to read upload/backups/.immich: Error: ENOENT: no such file or directory, open 'upload/backups/.immich'[39m
2025-06-18 18:41:28.039645+00:00microservices worker error: Error: Failed to read "<UPLOAD_LOCATION>/backups/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information.", stack: Error: Failed to read "<UPLOAD_LOCATION>/backups/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information."
2025-06-18 18:41:28.039716+00:00at StorageService.verifyReadAccess (/usr/src/app/dist/services/storage.service.js:84:19)
2025-06-18 18:41:28.039725+00:00at async /usr/src/app/dist/services/storage.service.js:38:21
2025-06-18 18:41:28.039731+00:00at async /usr/src/app/dist/repositories/database.repository.js:377:27
2025-06-18 18:41:28.039747+00:00at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20
2025-06-18 18:41:28.039755+00:00at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
2025-06-18 18:41:28.039762+00:00at async /usr/src/app/dist/repositories/database.repository.js:374:13
2025-06-18 18:41:28.046668+00:00microservices worker exited with code 1
```

**Comment by Adrian-Grimm** [comment]
OK - fixed it with just a `touch .immich`

https://immich.app/docs/administration/system-integrity/#folder-checks
