### ISSUE TITLE
Immich Cuda ML doesn't work after upgrade to 24.10

### ISSUE THREAD

**Issue by Karmalakas** [truenas/apps#942]
I'm experiencing issue with Machine Learning on Immich with nVidia GPU. It worked perfectly on 24.04, but not any more. Issue seems pretty much the same as @Fireflaker [reported on charts repo](https://github.com/truenas/charts/issues/2891)

Immich server log is flooded with:
```
2024-11-16 10:44:02.863611+00:00[31m[Nest] 7  - [39m11/16/2024, 12:44:02 PM [31m  ERROR[39m [33m[Microservices:JobService][39m [31mUnable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://machine-learning:32002" failed with SocketError: other side closed[39m
2024-11-16 10:44:02.863694+00:00[31m[Nest] 7  - [39m11/16/2024, 12:44:02 PM [31m  ERROR[39m [33m[Microservices:JobService][39m [31mError: Machine learning request to "http://machine-learning:32002" failed with SocketError: other side closed
2024-11-16 10:44:02.863704+00:00at /usr/src/app/dist/repositories/machine-learning.repository.js:18:19
2024-11-16 10:44:02.863710+00:00at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:17:21)
2024-11-16 10:44:02.863717+00:00at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:41:26)
2024-11-16 10:44:02.863722+00:00at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:104:27)
2024-11-16 10:44:02.863815+00:00at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:151:28)
2024-11-16 10:44:02.863825+00:00at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
2024-11-16 10:44:02.863831+00:00at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-11-16 10:44:02.863836+00:00at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)[39m
2024-11-16 10:44:02.863842+00:00[31m[Nest] 7  - [39m11/16/2024, 12:44:02 PM [31m  ERROR[39m [33m[Microservices:JobService][39m [31mObject:[39m
2024-11-16 10:44:02.863847+00:00{
2024-11-16 10:44:02.863852+00:00"id": "8c98c344-a218-4a31-9e82-f813f3cabf19"
2024-11-16 10:44:02.863858+00:00}
```

Immich ML log is flooded with:
```
2024-11-16 10:45:03.852444+00:00[2;36m[11/16/24 10:45:03][0m[2;36m [0m[1;31mERROR   [0m Worker [1m([0mpi[1;92md:530[0m[1m)[0m was sent code [1;36m139[0m!                
2024-11-16 10:45:03.858795+00:00[2;36m[11/16/24 10:45:03][0m[2;36m [0m[34mINFO    [0m Booting worker with pid: [1;36m559[0m                       
2024-11-16 10:45:07.993221+00:00[2;36m[11/16/24 10:45:07][0m[2;36m [0m[34mINFO    [0m Started server process [1m[[0m[1;36m559[0m[1m][0m                       
2024-11-16 10:45:07.993905+00:00[2;36m[11/16/24 10:45:07][0m[2;36m [0m[34mINFO    [0m Waiting for application startup.                   
2024-11-16 10:45:07.994840+00:00[2;36m[11/16/24 10:45:07][0m[2;36m [0m[34mINFO    [0m Created in-memory cache with unloading after 300s  
2024-11-16 10:45:07.994858+00:00[2;36m                    [0m         of inactivity.                                     
2024-11-16 10:45:07.995577+00:00[2;36m[11/16/24 10:45:07][0m[2;36m [0m[34mINFO    [0m Initialized request thread pool with [1;36m4[0m threads.    
2024-11-16 10:45:07.996317+00:00[2;36m[11/16/24 10:45:07][0m[2;36m [0m[34mINFO    [0m Application startup complete.                      
2024-11-16 10:45:08.075695+00:00[2;36m[11/16/24 10:45:08][0m[2;36m [0m[34mINFO    [0m Loading visual model [32m'ViT-B-32__openai'[0m to memory  
2024-11-16 10:45:08.076902+00:00[2;36m[11/16/24 10:45:08][0m[2;36m [0m[34mINFO    [0m Setting execution providers to                     
2024-11-16 10:45:08.076931+00:00[2;36m                    [0m         [1m[[0m[32m'CUDAExecutionProvider'[0m, [32m'CPUExecutionProvider'[0m[1m][0m, 
2024-11-16 10:45:08.076954+00:00[2;36m                    [0m         in descending order of preference    
```

Face detect no longers works..
Smart search no longer works...

Is 24.10 even able to let apps use nVidia GPUs? 24.04 has this option to allocate GPUs in app config, but 24.10 only has "Passthrough non-nVidia GPUs only"...

Immich:
App Version: v1.120.2
Version: 1.7.4

TrueNAS ElectricEel-24.10.0.2

P. S. Not sure how much this is related, but also started getting lots of alerts:
> Quota exceeded on dataset Data/.system/cores. Used 79.82% (817.33 MiB of 1 GiB).

Which is because of Immich ML. I see one file being created and deleted a lot with different size and timestamp
```
admin@KarmaNAS[/var/db/system/cores]$ ls -la
total 396691
drwxr-xr-x 2 root root         3 Nov 16 12:51 .
drwxr-xr-x 9 root root         9 Nov  7 20:38 ..
-rw-r----- 1 root root 406130825 Nov 16 12:51 core.gunicorn.0.fbf801cbe7d54546aac4908311c9b87c.1762863.1731754266000000.zst
```

**Comment by Karmalakas** [comment]
So booted again 24.10, installed driver and now I see nVidia GPU:
![image](https://github.com/user-attachments/assets/19550205-07ad-465d-b710-82595f2bfc4b)

BUT... If I check the box and click _Update_, I get this:
```
FAILED

[EFAULT] Failed to render compose templates: Traceback (most recent call last): File "/usr/bin/apps_render_app", line 33, in sys.exit(load_entry_point('apps-validation==0.1', 'console_scripts', 'apps_render_app')()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main render_templates_from_path(args.path, args.values) File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path rendered_data = render_templates( ^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates ).render({'ix_lib': template_libs, 'values': test_values}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/docker-compose.yaml", line 11, in top-level template code {% set postgres = tpl.deps.postgres(values.consts.pgvecto_container_name, "pgvecto_image", pg_config, perm_container) %} ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deps.py", line 276, in postgres return PostgresContainer(self._render_instance, name, image, config, perms_instance) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deps.py", line 299, in __init__ c = self._render_instance.add_container(name, image) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/render.py", line 50, in add_container container = Container(self, name, image) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/container.py", line 61, in __init__ self.deploy: Deploy = Deploy(self._render_instance) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deploy.py", line 15, in __init__ self.resources: Resources = Resources(self._render_instance) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/resources.py", line 24, in __init__ self._auto_add_gpus_from_values() File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/resources.py", line 55, in _auto_add_gpus_from_values raise RenderError(f"Expected [uuid] to be set for GPU in slot [{pci}] in [nvidia_gpu_selection]") base_v2_0_15.error.RenderError: Expected [uuid] to be set for GPU in slot [0000:01:00.0] in [nvidia_gpu_selection]
```

and:
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 287, in do_update
    app = self.update_internal(job, app, data, trigger_compose=app['state'] != 'STOPPED')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 317, in update_internal
    update_app_config(app_name, app['version'], new_values, custom_app=app['custom_app'])
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 59, in update_app_config
    render_compose_templates(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 50, in render_compose_templates
    raise CallError(f'Failed to render compose templates: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed to render compose templates: Traceback (most recent call last):
  File "/usr/bin/apps_render_app", line 33, in <module>
    sys.exit(load_entry_point('apps-validation==0.1', 'console_scripts', 'apps_render_app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main
    render_templates_from_path(args.path, args.values)
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path
    rendered_data = render_templates(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates
    ).render({'ix_lib': template_libs, 'values': test_values})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/docker-compose.yaml", line 11, in top-level template code
    {% set postgres = tpl.deps.postgres(values.consts.pgvecto_container_name, "pgvecto_image", pg_config, perm_container) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deps.py", line 276, in postgres
    return PostgresContainer(self._render_instance, name, image, config, perms_instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deps.py", line 299, in __init__
    c = self._render_instance.add_container(name, image)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/render.py", line 50, in add_container
    container = Container(self, name, image)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/container.py", line 61, in __init__
    self.deploy: Deploy = Deploy(self._render_instance)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/deploy.py", line 15, in __init__
    self.resources: Resources = Resources(self._render_instance)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/resources.py", line 24, in __init__
    self._auto_add_gpus_from_values()
  File "/mnt/.ix-apps/app_configs/immich/versions/1.7.4/templates/library/base_v2_0_15/resources.py", line 55, in _auto_add_gpus_from_values
    raise RenderError(f"Expected [uuid] to be set for GPU in slot [{pci}] in [nvidia_gpu_selection]")
base_v2_0_15.error.RenderError: Expected [uuid] to be set for GPU in slot [0000:01:00.0] in [nvidia_gpu_selection]
```

**Comment by stavros-k** [comment]
Please see https://forums.truenas.com/t/docker-apps-and-uuid-issue-with-nvidia-gpu-after-upgrade-to-24-10/22547?u=stavros-k

**Comment by Karmalakas** [comment]
Great! This seems to have solved the GPU issue

Now I'm again having permissions issues 🤦‍♂️ Need to figure that out 😞

**Comment by Fireflaker** [comment]
Not sure if this might help with your permission issues or if you meant encryption. In general keep default app acl without ever smb into it.

![image](https://github.com/user-attachments/assets/bc01308a-87df-4a92-a767-3e562dc62d3c)


https://github.com/truenas/apps/issues/712

**Comment by Fireflaker** [comment]
The above solutions indeed solved the GPU issue, but smart search failure persists. I will open another issue to detail further.

**Comment by Karmalakas** [comment]
So it seems "Install nVidia drivers" was unchecked for whatever reason. Checked it again, and Apps service stopped - had to unset and set back the pool. After service restarted, still was experiencing the same. Decided to leave it alone for now, but then almost an hour later was adding another app and noticet nVidia GPU checkbox was back. Went to the app that requered it, but of course it gave an error about unassigned slot. So had to run the command for each app again :man_facepalming: It seems now it's working again, but is it only until next update..?

I will keep an eye on it and re-open the issue again if it's going to be the same situation
