### ISSUE TITLE
APP Qbittorrent issue 

### ISSUE THREAD

**Issue by Saberwolf64** [truenas/apps#997]
when installing qbittorrent using Scale lates version there are a few issues webui button brings you to a unauthorized webpage To get around this just add / to the webaddess will fix it and send you to the admin loggin pages 
![image](https://github.com/user-attachments/assets/4f848692-0c8e-4a07-8d2b-704f24847ca3)
![image](https://github.com/user-attachments/assets/5431a831-c81a-4881-92aa-221ae74d6b1a)

second issue found is when adding a storage location i have the current /downloads mounted to the host path when i try to update i get error complaining about it is all ready in use yet the is being set but to the ixvolume in the app template is unable to be updated after app has been installed at this current time it will not allow me to update unless i remove hostpath mapping to /downloads and it will not let me remap after the update. this is an iussue with the app template. ever sense we update to the new electrice eal we can not modify ixVolumes that were auto created they are grayed out no selection is avail after the init install.

 ```
Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/upgrade.py", line 72, in upgrade
    update_app_config(app_name, upgrade_version['version'], new_values)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 59, in update_app_config
    render_compose_templates(
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/ix_apps/lifecycle.py", line 50, in render_compose_templates
    raise CallError(f'Failed to render compose templates: {cp.stderr}')
middlewared.service_exception.CallError: [EFAULT] Failed to render compose templates: Traceback (most recent call last):
  File "/usr/bin/apps_render_app", line 33, in <module>
    sys.exit(load_entry_point('apps-validation==0.1', 'console_scripts', 'apps_render_app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 47, in main
    render_templates_from_path(args.path, args.values)
  File "/usr/lib/python3/dist-packages/catalog_templating/scripts/render_compose.py", line 19, in render_templates_from_path
    rendered_data = render_templates(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/catalog_templating/render.py", line 36, in render_templates
    ).render({'ix_lib': template_libs, 'values': test_values})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/.ix-apps/app_configs/qbittorrent/versions/1.1.6/templates/docker-compose.yaml", line 24, in top-level template code
    {% do c1.add_storage(store.mount_path, store) %}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/.ix-apps/app_configs/qbittorrent/versions/1.1.6/templates/library/base_v2_0_15/container.py", line 182, in add_storage
    self._storage.add(mount_path, config)
  File "/mnt/.ix-apps/app_configs/qbittorrent/versions/1.1.6/templates/library/base_v2_0_15/storage.py", line 87, in add
    raise RenderError(f"Mount path [{mount_path}] already used for another volume mount")
base_v2_0_15.error.RenderError: Mount path [/downloads] already used for another volume mount
```

**Comment by stavros-k** [comment]
Regarding the browser issue, its something that qbit itself blocks.
You don't even need to add the `/`. Just hit enter on the address bar without any modifications.

**Comment by Saberwolf64** [comment]
Thank you for that thought i was going crazy
